<!doctype html>
<html lang="gr">
<head>
    <!--<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>-->
    <?
    $this->inlineScript()
        //The files live inside the public folder
        ->appendFile($this->basePath('js/jquery-1.12.1.min.js'))
        ->appendFile($this->basePath('js/jquery-ui.min.js'))

        ->appendFile($this->basePath('js/project/scheduler/layout.js'))
        ->appendFile($this->basePath('js/project/scheduler/scheduler.js'))
        ->appendFile($this->basePath('js/project/scheduler/schedulerEvents.js'))
        ->appendFile($this->basePath('js/project/scheduler/utils.js'))
        ->appendFile($this->basePath('js/project/scheduler/mailWindow.js'))

        ->appendFile($this->basePath('js/scripts/demos.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxcore.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxLoader.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxTabs.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxlayout.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxribbon.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxbuttons.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxscrollbar.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxdata.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxdata.export.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxdate.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxscheduler.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxscheduler.api.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxdatetimeinput.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxmenu.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxcalendar.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxtooltip.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxwindow.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxcheckbox.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxtree.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxlistbox.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxdropdownlist.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxnumberinput.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxlistbox.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxdropdownlist.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxnumberinput.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxradiobutton.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxinput.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxnotification.js'))
        ->appendFile($this->basePath('js/jqwidgets/globalization/globalize.js'))

        ->appendFile($this->basePath('js/jqwidgets/globalization/globalize.GR.js'));
//        ->appendFile($this->basePath('js/jqwidgets/globalization/globalize.culture.de-DE.js'))
    ?>

    <link rel="stylesheet" href="<? echo $this->basePath('js/jqwidgets/styles/jqx.base.css')?>" type="text/css" />
    <link rel="stylesheet" href="<? echo $this->basePath('js/jqwidgets/styles/jqx.energyblue.css')?>" type="text/css" />
    <link rel="stylesheet" href="<? echo $this->basePath('js/jquery-ui.min.css')?>" type="text/css" />
    <link rel="stylesheet" href="<? echo $this->basePath('css/project/iris.css')?>" type="text/css" />


    <style>
        body, html {
            width: 100%;
            height: 100%;
            overflow: hidden;
            padding: 3px;
            box-sizing: border-box;
            margin: 0;
        }
        .jqx-scheduler-appointment {
            border-radius: 7px;
            /*min-height: 35px;*/
        }
        .jqx-scheduler-appointment-status {
            display:none;
        }
        .jqx-layout-pseudo-window-pin-icon {
            display:none;
        }
    </style>
</head>
<body>
<div id="schedulercontainer" >
    <div id="jqxLayout">
        <!--The panel content divs can have a flat structure-->
        <!--documentGroup-->

        <div id="lefttoppanel">
            <div data-container="Document1Panel">
                <div id='jqxTabs'>
                    <ul id="tablist" style='margin-left: 20px; visibility: hidden;'>
                        <li>Προβολή</li>
                        <li>Επιλογές</li>
                    </ul>
                    <div>
                        <?=$this->roleTree()?>
                    </div>
                    <div>
                        <div style='text-align: center; margin-top:20px;'>
                            <input style="width:80%; visibility: hidden;" type="button" value="Εξαγωγή εγγράφου Excel" id='excelExport' />
                        </div>
                        <div style='text-align: center;'>
                            <input style="width:80%; visibility: hidden;" type="button" value="Εξαγωγή σελίδας HTML" id='htmlExport' />
                        </div>
                    </div>
                </div>
            </div>
            <div data-container="Document2Panel">
                <div style='text-align: center; margin-top:20px;'>

                </div>
                </br>
                <div style='text-align: center;'>

                </div>
            </div>
        </div>

        <!--bottom tabbedGroup-->
        <div data-container="OutputPanel">
            <div id="outputContainer" style="width: 100%;height:100%;visibility: hidden;">
                    <img src="/img/emblima.png" style="float: left; margin-left: 10px; height: 80px; position: relative; transform: perspective(1px) translateY(-50%); top: 50%;"/>
                    <div style="float: left; margin: 5px 0 0 10px; position: relative; top: 50%; transform: perspective(1px) translateY(-50%);">
                        <p>Όνομα: <?=$this->zfcUserIdentity()->getDisplayName()?></p>
                        <p>Γραφείο: <?=$this->zfcUserIdentity()->getRole()?></p>
                        <p>
                            <a href="<?php echo $this->url('zfcuser/logout') ?>" class="follow">
                                <img src="/img/logout1.png" style="float: left; height: 20px;"/>
                                <span style="margin-left: 5px;"><?php echo $this->translate('Αποσύνδεση'); ?></span>
                            </a>
                        </p>
                        <p>
                            <a href="<?php echo $this->url('zfcuser/changepassword') ?>" class="follow">
                                <img src="/img/password.png" style="float: left; height: 20px;"/>
                                <span style="margin-left: 5px;"><?php echo $this->translate('Αλλαγή Κωδικού'); ?></span>
                            </a>
                        </p>
                    </div>
            </div>
        </div>
        <!--right tabbedGroup-->
        <div data-container="SolutionExplorerPanel">
            <div id="scheduler"></div>
            <div id="messageNotification">
                <div id="messageNotificationText"></div>
            </div>
        </div>
    </div>
    <div>
        <input  style="visibility: hidden;" type="image" src="<?= $this->basePath().'/img/emaillogo.png'?>" id="showWindowButton" class="MailButton"/>
    </div>
</div>
<div id='jqxwindow'>
    <div>Header</div>
    <div id="content"></div>
</div>
</body>
</html>





