<!doctype html>
<html lang="gr">
<head>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <?
    $this->inlineScript()
        //The files live inside the public folder
        //->appendFile($this->basePath('js/scripts/jquery-1.11.1.min.js'))

        ->appendFile($this->basePath('js/project/scheduler/layout.js'))
        ->appendFile($this->basePath('js/project/scheduler/scheduler.js'))
        ->appendFile($this->basePath('js/project/scheduler/schedulerEvents.js'))
        ->appendFile($this->basePath('js/project/scheduler/utils.js'))
        ->appendFile($this->basePath('js/project/scheduler/mailWindow.js'))

        ->appendFile($this->basePath('js/scripts/demos.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxcore.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxLoader.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxTabs.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxlayout.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxribbon.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxbuttons.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxscrollbar.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxdata.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxdata.export.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxdate.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxscheduler.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxscheduler.api.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxdatetimeinput.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxmenu.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxcalendar.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxtooltip.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxwindow.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxcheckbox.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxtree.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxlistbox.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxdropdownlist.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxnumberinput.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxlistbox.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxdropdownlist.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxnumberinput.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxradiobutton.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxinput.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxnotification.js'))
        ->appendFile($this->basePath('js/jqwidgets/globalization/globalize.js'))

        ->appendFile($this->basePath('js/jqwidgets/globalization/globalize.GR.js'));
//        ->appendFile($this->basePath('js/jqwidgets/globalization/globalize.culture.de-DE.js'))
    ?>

    <link rel="stylesheet" href="<? echo $this->basePath('js/jqwidgets/styles/jqx.base.css')?>" type="text/css" />
    <link rel="stylesheet" href="<? echo $this->basePath('js/jqwidgets/styles/jqx.darkblue.css')?>" type="text/css" />
    <link rel="stylesheet" href="<? echo $this->basePath('css/project/mail.css')?>" type="text/css" />


    <style>
        body, html {
            width: 100%;
            height: 100%;
            overflow: hidden;
            padding: 3px;
            box-sizing: border-box;
            margin: 0;
        }
    </style>
</head>
<body>
<div id="schedulercontainer" >
    <div id="jqxLayout">
        <!--The panel content divs can have a flat structure-->
        <!--documentGroup-->

        <div id="lefttoppanel">
            <div data-container="Document1Panel">
                <div id='jqxTabs'>
                    <ul id="tablist" style='margin-left: 20px; visibility: hidden;'>
                        <li>Προβολή</li>
                        <li>Επιλογές</li>
                    </ul>
                    <div>
                        <?=$this->roleTree()?>
                    </div>
                    <div>
                        <div style='text-align: center; margin-top:20px;'>
                            <input style="width:80%; visibility: hidden;" type="button" value="Εξαγωγή εγγράφου Excel" id='excelExport' />
                        </div>
                        <div style='text-align: center;'>
                            <input style="width:80%; visibility: hidden;" type="button" value="Εξαγωγή σελίδας HTML" id='htmlExport' />
                        </div>
                    </div>
                </div>
            </div>
            <div data-container="Document2Panel">
                <div style='text-align: center; margin-top:20px;'>

                </div>
                </br>
                <div style='text-align: center;'>

                </div>
            </div>
        </div>

        <!--bottom tabbedGroup-->
        <div data-container="OutputPanel">
            </div>
        <!--right tabbedGroup-->
        <div data-container="SolutionExplorerPanel">
            <div id="scheduler"></div>
            <div id="messageNotification">
                <div id="messageNotificationText"></div>
            </div>
        </div>
    </div>
    <div>
        <input  style="visibility: hidden;" type="image" src="<?= $this->basePath().'/img/emaillogo.png'?>" id="showWindowButton" class="MailButton"/>
    </div>
</div>
<div id='jqxwindow'>
    <div>Header</div>
    <div id="content"></div>
</div>
</body>
</html>





