<?
$this->inlineScript()
    //The files live inside the public folder
    ->appendFile($this->basePath('js/project/scheduler/layout.js'))
    ->appendFile($this->basePath('js/project/scheduler/scheduler.js'))
    ->appendFile($this->basePath('js/project/scheduler/schedulerEvents.js'))
    ->appendFile($this->basePath('js/project/scheduler/utils.js'))

    ->appendFile($this->basePath('js/scripts/jquery-1.11.1.min.js'))
    ->appendFile($this->basePath('js/scripts/demos.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxcore.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxlayout.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxribbon.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxbuttons.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxscrollbar.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxdata.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxdate.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxscheduler.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxscheduler.api.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxdatetimeinput.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxmenu.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxcalendar.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxtooltip.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxwindow.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxcheckbox.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxtree.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxlistbox.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxdropdownlist.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxnumberinput.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxlistbox.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxdropdownlist.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxnumberinput.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxradiobutton.js'))
    ->appendFile($this->basePath('js/jqwidgets/jqxinput.js'))
    ->appendFile($this->basePath('js/jqwidgets/globalization/globalize.js'))
    ->appendFile($this->basePath('js/jqwidgets/globalization/globalize.culture.de-DE.js'))

?>
<link rel="stylesheet" href="<? echo $this->basePath('js/jqwidgets/styles/jqx.base.css')?>" type="text/css" />
<link rel="stylesheet" href="<? echo $this->basePath('js/jqwidgets/styles/jqx.darkblue.css')?>" type="text/css" />


<style>
    body, html {
        width: 100%;
        height: 100%;
        overflow: hidden;
        padding: 3px;
        box-sizing: border-box;
        margin: 0;
    }
</style>

<div id="jqxLayout">
    <!--The panel content divs can have a flat structure-->
    <!--documentGroup-->
    <div data-container="Document1Panel">
        <div id='jqxTree' style='visibility: hidden; float: left;'>
            <ul>
                <li item-checked='true' item-expanded='true'>1o ΕΓ
                    <ul>
                        <li>1o ΕΓ - Βοηθοί 1</li>
                        <li>1o ΕΓ - Βοηθοί 2</li>
                    </ul>
                </li>
                <li>2ο ΕΓ
                    <ul>
                        <li>2o ΕΓ - Βοηθοί 1</li>
                        <li>2o ΕΓ - Βοηθοί 2</li>
                    </ul>
                </li>
                <li item-checked='true' item-expanded='true'>ΔΔΒ
                    <ul>
                        <li>ΔΔΒ - Βοηθοί 1</li>
                        <li>ΔΔΒ - Βοηθοί 2</li>
                    </ul>
                </li>
                <li>ΓΕΠ
                    <ul>
                        <li>ΓΕΠ - Βοηθοί 1</li>
                        <li>ΓΕΠ - Βοηθοί 2</li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
    <div data-container="Document2Panel">
        Document 2 content</div>
    <!--bottom tabbedGroup-->
    <div data-container="OutputPanel">
        Output</div>
    <!--right tabbedGroup-->
    <div data-container="SolutionExplorerPanel">
        <div id="scheduler"></div></div>
</div>



