<!DOCTYPE html>
<html lang="el">
<head>
    <link rel="stylesheet" href="<? echo $this->basePath('js/jqwidgets/styles/jqx.base.css')?>" type="text/css" />
    <link rel="stylesheet" href="<? echo $this->basePath('js/jqwidgets/styles/jqx.darkblue.css')?>" type="text/css" />
    <link rel="stylesheet" href="<? echo $this->basePath('css/project/mail.css')?>" type="text/css" />
    <?
    $this->inlineScript()
        //The files live inside the public folder
        ->appendFile($this->basePath('js/project/mail/sampleData.js'))
        ->appendFile($this->basePath('js/project/mail/dataTable.js'))
        ->appendFile($this->basePath('js/project/mail/mailEvents.js'))
        ->appendFile($this->basePath('js/project/mail/menus.js'))
        ->appendFile($this->basePath('js/project/mail/layout.js'))


        ->appendFile($this->basePath('js/scripts/jquery-1.11.1.min.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxcore.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxlayout.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxdockpanel.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxmenu.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxinput.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxdata.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxeditor.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxlistbox.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxbuttons.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxscrollbar.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxdropdownlist.js'))

        ->appendFile($this->basePath('js/jqwidgets/jqxdropdownbutton.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxcolorpicker.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxwindow.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxtooltip.js'))

        ->appendFile($this->basePath('js/jqwidgets/jqxdatatable.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxgrid.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxgrid.sort.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxgrid.pager.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxgrid.selection.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxgrid.edit.js'))

        ->appendFile($this->basePath('js/jqwidgets/globalization/globalize.js'))
        ->appendFile($this->basePath('js/jqwidgets/globalization/globalize.culture.de-DE.js'))

    ?>
    <style>
        html, body {
            width: 100%;
            height: 100%;
            overflow: hidden;
            padding: 3px;
            box-sizing: border-box;
            margin: 0;
        }
    </style>
</head>

<body>
    <!--<div id="jqxDockPanel" style="width: auto; height: 100%;">
        <!--left menu
        <div dock='left' style="padding-right:4px">
            <input type="text" id="Search" style=" margin-bottom:4px"/>
            <div id='LeftMenu' style="visibility: hidden;">
                <ul>
                    <li id="first"><a href="#">Εισερχόμενα</a></li>
                    <li id="second"><a href="#">Απεσταλμένα</a></li>
                    <li id="third"><a href="#">Πρόχειρα</a></li>
                </ul>
            </div>
        </div>
        <!--top menu
        <div id='TopMenu' dock='top' style="visibility:">
            <ul name="myList">
                <!--
                <li><a href="#">Δημιουργία</a></li>
                <li><a href="#">Διαγραφή</a></li>
                <li><a href="#">Απάντηση</a></li>

            </ul>
        </div>
        <!--mailarea
        <div id='MailTable'>
            </div>
    </div>
    <div class="container">

        <div class="col-1" id="leftarea1">
            <input type="text" id="Search"/>
            <div id='LeftMenu' style="visibility:visible;">
                papakia
            </div>
        </div>

        <div class="col-2" id='TopMenu' style="visibility:visible; display:inline-block;">
            papakia 1
        </div>

        <div class="col-2" id='MailTable'>
            papakia 2
        </div>

    </div>-->
    <div>
        <img src='../../../img/emaillogo.png' alt="Email" height="30" style="float:left; margin-left:50px;">
        <div class="header" id='TopMenu' style="visibility:hidden;">
        </div>
    </div>
    <div class="menu">
        <div  id='LeftMenu' style="visibility:hidden;">
        </div>
    </div>
    <div class="main">
        <div  id='MailTable' style="visibility:hidden;"></div>

        <div id="creation" style="display: none">
            <div id="inputs">
                <input id="inputReceiver"/>
                <input id="inputSubject"/>
            </div>
            <div id="text"></div>
        </div>

    </div>


</body>
