<!DOCTYPE html>
<html lang="en">
<head>
    <?
    $this->inlineScript()
        //The files live inside the public folder


        ->appendFile($this->basePath('js/scripts/jquery-1.11.1.min.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxcore.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxlayout.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxnavbar.js'))

        ->appendFile($this->basePath('js/jqwidgets/jqxdockpanel.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxmenu.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxinput.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxdata.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxeditor.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxlistbox.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxbuttons.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxscrollbar.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxdropdownlist.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxribbon.js'))

        ->appendFile($this->basePath('js/jqwidgets/jqxdropdownbutton.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxcolorpicker.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxwindow.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxtooltip.js'))

        ->appendFile($this->basePath('js/jqwidgets/jqxgrid.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxgrid.sort.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxgrid.pager.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxgrid.selection.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxgrid.edit.js'))
        ->appendFile($this->basePath('js/jqwidgets/jqxcheckbox.js'))

        ->appendFile($this->basePath('js/jqwidgets/globalization/globalize.GR.js'))

    ?>

    <link rel="stylesheet" href="<? echo $this->basePath('js/jqwidgets/styles/jqx.base.css')?>" type="text/css" />
    <link rel="stylesheet" href="<? echo $this->basePath('js/jqwidgets/styles/jqx.energyblue.css')?>" type="text/css" />
    <link rel="stylesheet" href="<? echo $this->basePath('css/project/iris.css')?>" type="text/css" />
    <script type="text/javascript">
        $(document).ready(function () {
            // prepare the data
            var data = new Array();
            var firstNames =
                [
                    "Andrew", "Nancy", "Shelley", "Regina", "Yoshi", "Antoni", "Mayumi", "Ian", "Peter", "Lars", "Petra", "Martin", "Sven", "Elio", "Beate", "Cheryl", "Michael", "Guylene"
                ];
            var lastNames =
                [
                    "Fuller", "Davolio", "Burke", "Murphy", "Nagase", "Saavedra", "Ohno", "Devling", "Wilson", "Peterson", "Winkler", "Bein", "Petersen", "Rossi", "Vileid", "Saylor", "Bjorn", "Nodier"
                ];
            var productNames =
                [
                    "Black Tea", "Green Tea", "Caffe Espresso", "Doubleshot Espresso", "Caffe Latte", "White Chocolate Mocha", "Cramel Latte", "Caffe Americano", "Cappuccino", "Espresso Truffle", "Espresso con Panna", "Peppermint Mocha Twist"
                ];
            var priceValues =
                [
                    "2.25", "1.5", "3.0", "3.3", "4.5", "3.6", "3.8", "2.5", "5.0", "1.75", "3.25", "4.0"
                ];
            for (var i = 0; i < 200; i++) {
                var row = {};
                var productindex = Math.floor(Math.random() * productNames.length);
                var price = parseFloat(priceValues[productindex]);
                var quantity = 1 + Math.round(Math.random() * 10);
                row["firstname"] = firstNames[Math.floor(Math.random() * firstNames.length)];
                row["lastname"] = lastNames[Math.floor(Math.random() * lastNames.length)];
                row["productname"] = productNames[productindex];
                row["price"] = price;
                row["quantity"] = quantity;
                row["total"] = price * quantity;
                data[i] = row;
            }
            var source =
            {
                localdata: data,
                datatype: "observableArray",
                datafields:
                    [
                        { name: 'firstname', type: 'string' },
                        { name: 'lastname', type: 'string' },
                        { name: 'productname', type: 'string' },
                        { name: 'quantity', type: 'number' },
                        { name: 'price', type: 'number' },
                        { name: 'total', type: 'number' }
                    ]
            };
            var dataAdapter = new $.jqx.dataAdapter(source,
                {
                    formatData: function (data) {
                        data.firstname_startsWith == $("#searchField").val(); //to be continued
                        return data;
                }
            });

            $("#jqxgrid").jqxGrid(
                {
                    width: 850,
                    source: dataAdapter,
                    showtoolbar: true,
                    rendertoolbar: function (toolbar) {
                        var me = this;
                        var container = $("<div style='margin: 5px;'></div>");
                        var span = $("<span style='float: left; margin-top: 5px; margin-right: 4px;'>Αναζήτηση μηνύματος: </span>");
                        var input = $("<input class='jqx-input jqx-widget-content jqx-rc-all' id='searchField' type='text' style='height: 23px; float: left; width: 223px;' />");
                        toolbar.append(container);
                        container.append(span);
                        container.append(input);
/*                        if (theme != "") {
                            input.addClass('jqx-widget-content-' + theme);
                            input.addClass('jqx-rc-all-' + theme);
                        }*/
                        var oldVal = "";
                        input.on('keydown', function (event) {
                            if (input.val().length >= 2) {
                                if (me.timer) {
                                    clearTimeout(me.timer);
                                }
                                if (oldVal != input.val()) {
                                    me.timer = setTimeout(function () {
                                        $("#jqxgrid").jqxGrid('updatebounddata');
                                    }, 1000);
                                    oldVal = input.val();
                                }
                            }
                            else {
                                $("#jqxgrid").jqxGrid('updatebounddata');
                            }
                        })
                    },
                    columns: [
                        { text: 'Name', datafield: 'firstname', width: 120 },
                        { text: 'Last Name', datafield: 'lastname', width: 120 },
                        { text: 'Product', datafield: 'productname', width: 180 },
                        { text: 'Quantity', datafield: 'quantity', width: 80, cellsalign: 'right' },
                        { text: 'Unit Price', datafield: 'price', width: 90, cellsalign: 'right', cellsformat: 'c2' },
                        { text: 'Total', datafield: 'total', cellsalign: 'right', cellsformat: 'c2' }
                    ]
                });
        });
    </script>
</head>
<body class='default'>
<div id='jqxWidget'>
    <div id="jqxgrid">
    </div>
</div>
</body>
</html>